### ISSUE TITLE
Add a "Frameworks" section

### ISSUE THREAD

**Issue by phosphore** [lirantal/awesome-nodejs-security#41]
Hey!
Thank you @lirantal for creating this neat list. Would it be possible to add a section framework, with links pointing to Express, Sails, Electron lists or resources? I can propose a draft for it if you like.

Thanks!

**Comment by phosphore** [comment]
Forgot the "security" word in my original submission, but yeah that was my initial intention, sorry! 😂
I'll try to carve out time on my schedule in the next days for gathering a few entries for this list.

**Comment by lirantal** [comment]
Sounds good 👍

**Comment by lirantal** [comment]
Closing for now :-)
Feel free to work it out in a future PR
