### ISSUE TITLE
https://nodesecroadmap.fyi leads to 404

### ISSUE THREAD

**Issue by php-coder** [lirantal/awesome-nodejs-security#42]
I'm not sure whether it's a temporary or we should remove it from the list.

**Comment by mikesamuel** [comment]
I'll fix it.

I had it served via Google's appengine deployment.
I left Google though so I think their spring cleaning must have shut it down.

I still control that origin, so I'll redeploy somewhere else.

**Comment by mikesamuel** [comment]
Thanks for the report, btw.

**Comment by mikesamuel** [comment]
I ran into a problem.  I control the domain but Google still controls the old appengine app.  I think I've got it sorted by following https://stackoverflow.com/questions/46345759/error-domain-is-already-mapped-to-a-project-in-google-cloud-platform so I'll check after DNS has had time to trickle.

In the meantime https://node-sec-roadmap-fyi.uc.r.appspot.com/ should work.

**Comment by lirantal** [comment]
Original domain works fine. Thanks @php-coder for bringing up and the quick fix @mikesamuel ❤️
