### ISSUE TITLE
Idea: would be nice to have a table list for the incidents

### ISSUE THREAD

**Issue by lirantal** [lirantal/awesome-nodejs-security#67]
Right now the incidents are just a list.
Would be great to:
1. Have them sorted out in a table so it is easier to access links, names, etc
2. Include dates of each incident
3. Order them by date descending so newest is on top and is easier to find

**Comment by usamavarikkottil** [comment]
Hello @lirantal, 
Resolved this issue in PR #73. Please close this issue.

**Comment by lirantal** [comment]
This is truly awesome, thank you!

**Comment by usamavarikkottil** [comment]
Should we convert the markdown table into an HTML table, @lirantal? The Readme file will be clean and more readable then.

**Comment by lirantal** [comment]
I think it's ok leaving as plain markdown at the moment so we stay consistent across the document. Let's see if the need arises in the future to set it up in a different way.
