### ISSUE TITLE
Is companies section is ok for an Open source org ?

### ISSUE THREAD

**Issue by fraxken** [lirantal/awesome-nodejs-security#68]
Hello @lirantal 👋,

Would it be ok to add [NodeSecure](https://github.com/NodeSecure) to the companies section ? There is no vocation to create a legal structure but we put ourselves forward as an organization of developers working together in order to create security tools.

Maybe a new section ?

Best Regards,
Thomas

**Comment by lirantal** [comment]
Yes, that sounds ok to me and good to increase more awareness of NodeSecure.
