### ISSUE TITLE
Add a section for recorded talks ?

### ISSUE THREAD

**Issue by fraxken** [lirantal/awesome-nodejs-security#75]
I thought it would be nice to have a section for talks related to Node.js security. What do you think ? (I can PR a bunch of talks i have in favorite if you are ok with the idea).

**Comment by lirantal** [comment]
Possibly, I just wouldn't want it to turn into competitor staging area :-)

**Comment by MichalPorag** [comment]
@lirantal Can I take it?

**Comment by lirantal** [comment]
Definitely :-)

**Comment by lirantal** [comment]
OMG are you going to do a live contribution Michal ??? 😱👑
