### ISSUE TITLE
Link to 'A Roadmap for Node.js Security' not working

### ISSUE THREAD

**Issue by patric-eberle** [lirantal/awesome-nodejs-security#79]
It seems that the link to [A Roadmap for Node.js Security](https://nodesecroadmap.fyi/) is dead. The proposed link on https://github.com/lirantal/awesome-nodejs-security/issues/42#issuecomment-646128936 does work though. It might better be replaced in the documentation.

**Comment by lirantal** [comment]
Ahh indeed, would you like to shoot a PR to make the update?

**Comment by fraxken** [comment]
I close since it's corrected. Thanks for the contribution ❤️.
