### ISSUE TITLE
What about OpenSSF initiatives/tools?

### ISSUE THREAD

**Issue by fraxken** [lirantal/awesome-nodejs-security#90]
I think could be cool to add links to some Open source initiatives like:

- [Scorecard](https://securityscorecards.dev/)
- [SLSA](https://slsa.dev/) (and maybe also sigstore.. But I'm working on few things around that for Node so I may add it later).

Also not sure how to also put [OSV](https://osv.dev/) ?

What do you think?

**Comment by lirantal** [comment]
Yes definitely but can we find the specific Node.js angles to add those? with OSV it's easy as we can add it with the npm registry specific link.

Perhaps we can do something similar for the above related to the Node.js project or other projects?

**Comment by fraxken** [comment]
I guess for Scorecard the last article I added is quite good. And I'm working on SLSA/Sigstore on NodeSecure (I plan to write an article.. I Just have so much things to do not sure when haha).
