### ISSUE TITLE
Hardened JavaScript

### ISSUE THREAD

**Issue by kriskowal** [lirantal/awesome-nodejs-security#95]
Would you be open to a change to include:

* [`ses`](https://github.com/endojs/endo/tree/master/packages/ses#ses), a shim for “Hardened JavaScript” which creates sub-realm sandboxes (`Compartment`) and freezes all intrinsics shared between them?
* [LavaMoat](https://github.com/lavamoat/lavamoat) which uses Hardened JavaScript to confine third-party dependencies (`node_modules`) using human-readable policies generated from static analysis?
* [Moddable](https://github.com/Moddable-OpenSource/moddable) which uses Hardened JavaScript to confine JavaScript programs on embedded systems?

**Comment by lirantal** [comment]
Yes, 100% @kriskowal
